stages:
  data_collection:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/features/build_features.py
    deps:
    - data/raw
    - src/features/build_features.py
    outs:
    - data/processed
